services:
  - type: web
    name: safebuild-web-detector
    env: python
    plan: free
    region: oregon
  buildCommand: pip install -r requirements.txt
  # Use gunicorn to run the Flask app defined in flask_server.py
  startCommand: gunicorn flask_server:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
